version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install  # Install Node.js dependencies (including steganography)
  build:
    commands:
      - echo "Building the application..."
      - node encryptTextToImage.js  # Run the encryption script (convert text to image)
      - node decryptImageToText.js  # Optionally, run the decryption to verify the process
      - echo Build complete.
  post_build:
    commands:
      - echo Post-build steps...
      - echo Preparing for deployment...
artifacts:
  files:
    - '**/*'
    - 'output_image.png'  # Ensure this is the output file you want to deploy
  base-directory: 'dist'  # Adjust if your build files are located elsewhere
